name: CI

on:
  # push:
  #   paths:
  #     - '**.zig'
  # pull_request:
  #    paths:
  #     - '**.zig'
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Grab zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      
      - name: Lint
        run: zig fmt --check --ast-check **.zig
        
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Grab zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      
      - name: Test
        run: zig build test
        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Grab zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      
      - name: Build
        run: zig build install
