name: CI

on:
  push:
    paths:
      - '**.zig'
      - 'gyro.zzz'
  pull_request:
     paths:
      - '**.zig'
      - 'gyro.zzz'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      - uses: mattnite/setup-gyro@v1.1.0
      
      - name: build
        run: gyro build test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      - run: zig fmt --check --ast-check **.zig
