name: CI

on:
  push:
    paths:
      - '**.zig'
  pull_request:
     paths:
      - '**.zig'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      
      - name: Lint
        run: zig fmt --check --ast-check **.zig

      - name: Build
        run: zig build install

      - name: Test
        run: zig build test
