name: CI

on:
  push:
    paths:
      - '**.zig'
  pull_request:
     paths:
      - '**.zig'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      
      - name: build
        run: zig build -fno-stage1
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      - run: zig fmt --check --ast-check **.zig
